version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fsw-foods
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data:
